### ISSUE TITLE
R 3.5.0

### ISSUE THREAD

**Issue by Tai-Rocha** [gabrielhoc/Mapinguari#1]
Hi 
Is it possible to install Mapinguari package on 3.5 R version??
I tried so many time but it failed

Best regards
Tainá

**Comment by gabrielhoc** [comment]
Hi, Tainá!

I updated my R to 3.5 and reinstalled Mapinguari successfully, on a Windows computer. Which error message are you getting?

Thanks for the feedback

**Comment by Tai-Rocha** [comment]
Thanks Gabriel!! I fix my problem. I  was try to install through R. But i found command line to do it. Now everything works well!!

Thanks!!!
